name: Docker Image CI for GHCR

on: push

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Checkout repository
              run: docker login --username onurcansevinc --password ${{ secrets.GH_PAT }} ghcr.io
                  docker build . --tag ghcr.io/onurcansevinc/puppeter-nodejs:latest
                  docker push ghcr.io/onurcansevinc/puppeter-nodejs:latest
