name: Docker Image CI for GHCR

on: push

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Docker image
              run: docker build -t ghcr.io/onurcansevinc/puppeter-nodejs:latest .

            - name: Push Docker image
              run: docker push ghcr.io/onurcansevinc/puppeter-nodejs:latest
